package view;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import static com.itextpdf.text.Font.ITALIC;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.MyConnect;
import static view.MainFrame.setJTableColumnsWidth;

public class GDThongKeSach extends javax.swing.JFrame {

    private MyConnect myConn;
    private PreparedStatement ps;
    private ResultSet rs;

    /**
     * Creates new form GDThongKeSach
     */
    public GDThongKeSach() {
        initComponents();
        this.setTitle("Thư viện Trường Đại học Bách Khoa Hà Nội");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setJTableColumnsWidth(jTable1, 1028, 70, 30);// Chia tỉ lệ độ rộng cho các cột
        myConn = new MyConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thống kê sách");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên sách", "Theo tác giả", "Theo nhà xuất bản" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tiêu chí", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Xuất File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Trở lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            this.dispose();
            MainFrame mf = new MainFrame();
            mf.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GDThemSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        // Thống kê theo tên sách
        if (jComboBox1.getSelectedIndex() == 0) {
            String sql = "SELECT tensach,COUNT(tensach) AS Count FROM quanlythuvien.sach GROUP BY tensach";
            try {
                ps = myConn.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                Vector cols = new Vector();
                Vector data = new Vector();
                cols.add("Tên sách");
                cols.add("Số lượng");
                while (rs.next()) {

                    Vector s = new Vector();
                    s.add(rs.getString("tensach"));
                    s.add(rs.getInt("Count"));
                    data.add(s);
                    jTable1.setModel(new DefaultTableModel(data, cols));
                    setJTableColumnsWidth(jTable1, 1028, 70, 30);// Chia tỉ lệ độ rộng cho các cột
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        // Thống kê theo tác giả
        if (jComboBox1.getSelectedIndex() == 1) {
            String sql = "SELECT tacgia,COUNT(tacgia) AS Count FROM quanlythuvien.sach GROUP BY tacgia";
            try {
                ps = myConn.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                Vector cols = new Vector();
                Vector data = new Vector();
                cols.add("Tác giả");
                cols.add("Số lượng sách");
                while (rs.next()) {

                    Vector s = new Vector();
                    s.add(rs.getString("tacgia"));
                    s.add(rs.getInt("Count"));
                    data.add(s);
                    jTable1.setModel(new DefaultTableModel(data, cols));
                    setJTableColumnsWidth(jTable1, 1028, 70, 30);// Chia tỉ lệ độ rộng cho các cột
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        // Thống kê theo nhà xuất bản
        if (jComboBox1.getSelectedIndex() == 2) {
            String sql = "SELECT nhaxuatban,COUNT(nhaxuatban) AS Count FROM quanlythuvien.sach GROUP BY nhaxuatban";
            try {
                ps = myConn.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                Vector cols = new Vector();
                Vector data = new Vector();
                cols.add("Nhà xuất bản");
                cols.add("Số lượng sách");
                while (rs.next()) {

                    Vector s = new Vector();
                    s.add(rs.getString("nhaxuatban"));
                    s.add(rs.getInt("Count"));
                    data.add(s);
                    jTable1.setModel(new DefaultTableModel(data, cols));
                    setJTableColumnsWidth(jTable1, 1028, 70, 30);// Chia tỉ lệ độ rộng cho các cột
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        if (model1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa có dữ liệu để xuất file !");
        } else {
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter ft = new FileNameExtensionFilter("PDF Documents", "pdf");
            chooser.addChoosableFileFilter(ft);
            int returnVal = chooser.showSaveDialog(this);
            if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                try {
                    String fileName = chooser.getSelectedFile().getName();
                    String dir = chooser.getCurrentDirectory().toString();
                    File f = new File(dir + "\\" + fileName + ".pdf");

                    if (f.exists()) {
                        JOptionPane.showMessageDialog(this, "Tên file đã tồn tại, mời bạn chọn tên khác !");
                    } else {
                        Document document = new Document(PageSize.A4, 50, 50, 10, 50);
                        PdfWriter writer;
                        writer = PdfWriter.getInstance(document, new FileOutputStream(dir + "\\" + fileName + ".pdf"));
                        document.open();

                        Font f1 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f1.setSize(10);
                        f1.setColor(BaseColor.BLACK);
                        document.add(new Paragraph("THƯ VIỆN BÁCH KHOA\n         IN ẤN SAO KÊ", f1));

                        Font f2 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f2.setSize(16);
                        f2.setColor(BaseColor.BLACK);
                        Paragraph p = new Paragraph("THỐNG KÊ SÁCH", f2);
                        p.setAlignment(Element.ALIGN_CENTER);
                        document.add(p);

                        Font f5 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f5.setSize(8);
                        f5.setColor(BaseColor.BLACK);
                        f5.setStyle(ITALIC);

                        Font f3 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f3.setSize(8);
                        f3.setColor(BaseColor.BLACK);

                        Font f6 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f6.setSize(8);
                        f6.setColor(BaseColor.BLACK);
                        f6.setStyle(ITALIC);

                        Font f7 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f7.setSize(8);
                        f7.setColor(BaseColor.BLACK);
                        PdfPTable t1 = new PdfPTable(new float[]{1, 1});
                        t1.setWidthPercentage(100);
                        t1.setTotalWidth(1200);
                        t1.setSpacingBefore(0);
                        t1.setSpacingAfter(0);
                        if (jComboBox1.getSelectedIndex() == 0) {
                            Paragraph p5 = new Paragraph("Thống kê sách theo mã sách\n\n", f6);
                            p5.setAlignment(Element.ALIGN_LEFT);
                            document.add(p5);
                            PdfPCell c11 = new PdfPCell(new Phrase("Tên Sách", f7));
                            t1.addCell(c11);
                            PdfPCell c12 = new PdfPCell(new Phrase("Số Lượng Sách", f7));
                            t1.addCell(c12);
                        }
                        if (jComboBox1.getSelectedIndex() == 1) {
                            Paragraph p5 = new Paragraph("Thống kê sách theo tác giả\n\n", f6);
                            p5.setAlignment(Element.ALIGN_LEFT);
                            document.add(p5);
                            PdfPCell c11 = new PdfPCell(new Phrase("Tác Giả", f7));
                            t1.addCell(c11);
                            PdfPCell c12 = new PdfPCell(new Phrase("Số Lượng Sách", f7));
                            t1.addCell(c12);
                        }
                        if (jComboBox1.getSelectedIndex() == 2) {
                            Paragraph p5 = new Paragraph("Thống kê sách theo nhà xuất bản\n\n", f6);
                            p5.setAlignment(Element.ALIGN_LEFT);
                            document.add(p5);
                            PdfPCell c11 = new PdfPCell(new Phrase("Nhà Xuất Bản", f7));
                            t1.addCell(c11);
                            PdfPCell c12 = new PdfPCell(new Phrase("Số Lượng Sách", f7));
                            t1.addCell(c12);
                        }

                        for (int i = 0; i < model1.getRowCount(); i++) {
                            t1.addCell(new Phrase(model1.getValueAt(i, 0).toString(), f3));
                            t1.addCell(new Phrase(model1.getValueAt(i, 1).toString(), f3));
                        }
                        document.add(t1);

                        Calendar cal = new GregorianCalendar();
                        int year = cal.get(Calendar.YEAR);
                        int month = cal.get(Calendar.MONTH);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        String date = (day + "/" + (month + 1) + "/" + year);
                        Font f4 = new Font(BaseFont.createFont("/assets/vuArial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                        f4.setSize(10);
                        f4.setColor(BaseColor.BLACK);
                        Paragraph p1 = new Paragraph("\nHà Nội , " + date, f4);
                        p1.setAlignment(Element.ALIGN_RIGHT);
                        document.add(p1);

                        document.close();
                        JOptionPane.showMessageDialog(this, "Lưu file thành công !");
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hủy bỏ !");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDThongKeSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
